spring.application.name=order-service

server.port=8082

# Deshabilitamos la configuración de JPA mientras no haya DB
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Eureka
# eureka.client.service-url.defaultZone=http://localhost:8761/eureka/ # LOCAL
eureka.client.service-url.defaultZone = ${URL_EUREKA:http://eureka-server:8761/eureka/}

# eureka.instance.hostname = order-service # Nombre del servicio para Eureka
eureka.instance.prefer-ip-address = true
# Usar IP en lugar de hostname para evitar problemas de resolución