spring.application.name=order-service

server.port=8082

# Deshabilitamos la configuración de JPA mientras no haya DB
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Eureka
# eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.service-url.defaultZone = https://eureka-server-ufvy.onrender.com/eureka/

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true